#Server Configuration
server:
  servlet:
    context-path: /planno

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
